version: 2
jobs:
  dependencies:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Login to dockerhub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Docker build
          command: docker build -t mbssantos/devops:latest .
      - run:
          name: Push to dockerhub
          command: docker push mbssantos/devops:latest

  lint:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm run lint-ci
      - run: npm run stylelint-ci

  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm run test

  verify-install:
    executor: azure-cli/default
    steps:
      - azure-cli/install
      - run:
          command: az -v
          name: Verify Azure CLI is installed

orbs:
  azure-cli: circleci/azure-cli@1.0.0
version: 2.1

workflows:
  version: 2
  build_and_test:
    jobs:
      - dependencies
      - build:
          requires:
            - dependencies
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
