version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.0.0

jobs:
  dependencies:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Login to container registry
          command: docker login $REGISTRY_NAME -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Docker build
          command: docker build -t $REGISTRY_NAMEIMAGE/devops:v2 .
      - run:
          name: Push image
          command: docker push $REGISTRY_NAMEIMAGE/devops:v2

  # deploy:
  #   docker:
  #     - image: docker:17.05.0-ce-git
  #   steps:
  #     - run:
  #         name: Tell k8s to update
  #         command: kubectl --record deployment.apps/fe-deployment set image deployment.v1.apps/fe-deployment react=devops123.azurecr.io/devops:v2
  #     - run:
  #         name: Wait for rollout
  #         command: kubectl rollout status deployment.v1.apps/fe-deployment
#
# kubectl --record devops123.azurecr.io/devops set image devops123.azurecr.io/devops devops=devops:v2
# kubectl --record deployment.apps/fe-deployment set image deployment.v1.apps/fe-deployment react=devops123.azurecr.io/devops:v1



        # docker login $REGISTRY_NAME -u $DOCKER_USER -p $DOCKER_PASS
        # docker push $REGISTRY_NAMEIMAGE/$DOCKER_IMAGE:$TAG
        # docker push $REGISTRY_NAMEIMAGE/$DOCKER_IMAGE:latest
        # echo "Pushed image: " $REGISTRY_NAMEIMAGE/$DOCKER_IMAGE:$TAG " and :latest tag"

  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm run test

  verify-install:
    executor: azure-cli/default
    steps:
      - azure-cli/install
      - run:
          command: az -v
          name: Verify Azure CLI is installed
      - run:
          name: Tell k8s to update
          command: kubectl --record deployment.apps/fe-deployment set image deployment.v1.apps/fe-deployment react=devops123.azurecr.io/devops:v2
      - run:
          name: Wait for rollout
          command: kubectl rollout status deployment.v1.apps/fe-deployment

  login-to-azure:
    executor: azure-cli/azure-docker
    steps:
      - azure-cli/login-with-service-principal
      - run:
          command: az resource list
          name: List resources of tenant stored as `AZURE_SP_TENANT` env var

  # "appId": "db53b921-bd36-46cd-baf7-6b20177c3680",
  # "displayName": "azure-cli-2019-05-10-21-43-34",
  # "name": "http://azure-cli-2019-05-10-21-43-34",
  # "password": "1941679a-5e75-4051-bc66-859d54f2d614",
  # "tenant": "df7432e9-2b1c-4ea6-93c6-89904adae8ac"

workflows:
  version: 2
  build_and_test:
    jobs:
      - dependencies
      # - verify-install
      # - login-to-azure:
      #     requires:
      #       - verify-install
      - build:
          requires:
            - dependencies
      - test:
          requires:
            - build
